apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-html-site
  namespace: default
  annotations:
    reloader.stakater.com/search: "true"
spec:
  selector:
    matchLabels:
      app: status
  replicas: 2
  template:
    metadata:
      labels:
        app: status
    spec:
      containers:
      - name: status
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
            - name: status-index-file
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: status-index-file
        configMap:
          name: status-index-html-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: status
  namespace: default
status:
  loadBalancer: {}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: status
  type: ClusterIP
  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static-tls-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd

spec:
  tls:
    - hosts:
        - status.galsandgardens.com
      secretName: status-tls
  rules:
    - host: status.galsandgardens.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: status
                port:
                  number: 80



---
apiVersion: v1
kind: ConfigMap
metadata:
  name: status-index-html-configmap
  namespace: default
  annotations:
    reloader.stakater.com/match: "true"
data:
  index.html: |
    <!doctype html>
    <html lang="en">
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Hugo 0.84.0">
        <title>Kate Taylor - Best Mom Ever.</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    
        
      </head>
      <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">Kate Taylor</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Best mom Ever?
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#">Damn Right.</a></li>
                    <li><a class="dropdown-item" href="#">Happy birthday mom.</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">I love you!</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">(From your favorite child - Mike)</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <div class="container">
          <img src="https://marketplace.canva.com/EAEyuMaeoOE/1/0/1600w/canva-happy-birthday-instagram-post-mFmsycgF9eM.jpg" class="img-fluid" alt="Moms Birthday!">
        </div>
    
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
      </body>
    </html>
